language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "nightly"

install:
  - pip install pipenv pycodestyle
  - pipenv install --dev

script:
  - pipenv run python -m jinjalint.test
  - pipenv run pycodestyle jinjalint/
